### ISSUE TITLE
Quality_flag

### ISSUE THREAD

**Issue by BANELE-MTHEMBU** [JonahDW/Image-processing#19]
I was running a `catalog_matching` file, I got the following error:

Traceback (most recent call last):
  File "catalog_matching.py", line 909, in <module>
    main()
  File "catalog_matching.py", line 782, in main
    pointing = Pointing(pointing_cat, pointing, survey_name, ra_center, dec_center, fov)
  File "catalog_matching.py", line 223, in __init__
    self.cat = catalog[catalog['Quality_flag'] == 1]
  File "/home/banele/anaconda3/lib/python3.8/site-packages/astropy/table/table.py", line 1872, in __getitem__
    return self.columns[item]
  File "/home/banele/anaconda3/lib/python3.8/site-packages/astropy/table/table.py", line 246, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'Quality_flag'

**Comment by JonahDW** [comment]
Hi, could you also include the command that you are running the script with?

**Comment by JonahDW** [comment]
Thanks! To generate the `img_cfp2020_1_full_1024ch_J0438-5419.ms_DDFkMS.app.restored_srl_bdsfcat.fits` catalog, did you use the `sourcefinding.py` script or your own PyBDSF recipe? 

The `sourcefinding.py` script should take care of everything and add the required info to the catalog. Furthermore, it extracts necessary information from the table meta and puts it in the catalog header in order to run `catalog_matching.py` effectively. You can do this while keeping your catalog intact by running `python sourcefinding.py catalog <your_image>  --redo_catalog img_cfp2020_1_full_1024ch_J0438-5419.ms_DDFkMS.app.restored_srl_bdsfcat.fits`

Hope that helps, but let me know if something is unclear.

**Comment by JonahDW** [comment]
With the changes in 011cba728caf9053562596698b59da355608335d, this error should not occur anymore under any circumstances, so I'm closing this now.
